services:
  - type: web
    name: tamam-shop
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: META_PIXEL_ID
        sync: false
      - key: META_ACCESS_TOKEN
        sync: false
      - key: IQD_TO_USD_RATE
        value: "1400"
      - key: GOOGLE_SHEET_WEBHOOK_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
